### PR TITLE
fix unit tests on older PHP versions by using non-namespaced bools

### PR DESCRIPTION
**Pull request by fkooman**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
Wait, I don't understand. How does non-namespaced bools break anything?

**Comment by peter279k** [comment]
On the old PHP versions, it will let PHP think it's the `this\is\namespace\false` and `this\is\namespace\true`.

To avoid this problem, add the `\` before bool to let PHP know this is the constant on root namespace.

**Comment by azjezz** [comment]
this is not an issue since `true` and `false` are not redeclared inside this namespace.

if you are redeclaring `true` and `false` ( regardless whether inside the lib namespace or not ), you are doing something very wrong.

@paragonie-scott see : https://3v4l.org/06UiY#v530

**Comment by fkooman** [comment]
That redeclaring happens here: https://github.com/paragonie/constant_time_encoding/blob/v1.x/tests/autoload.php, but why?

**Pull request merged**
