### PR TITLE
Those functions are global by defualt

### PR DESCRIPTION
**Pull request by Nenglish7**

### CODE REVIEW

**Comment by paragonie-scott** [comment]
The global namespace declaration is to prevent substitution attacks [as detailed here](https://github.com/simcop2387/underhanded-crypto/tree/master/ScottArcizewski).

**Comment by exussum12** [comment]
How about 

use function function_exists

Imo looks better than the backslash and functions the same. 5.6+ required though

**Comment by exussum12** [comment]
Also pre 7 null true false etc should have a backslash 

if ($length !== null) 

For example 

https://3v4l.org/AlUMd

**Comment by Nenglish7** [comment]
I now see why their is backslash, this can be closed.

**Pull request closed without merging**
