### PR TITLE
Hex::decode() optimizations

### PR DESCRIPTION
**Pull request by terrafrost**
I rewrote `Hex::decode()` in a way that yields a ~75% speedup over your existing implementation.

My benchmark code:

```php
use ParagonIE\ConstantTime\Hex;

$start = microtime(true);
for ($i = 1; $i < 5000; $i++) {
    $orig = random_bytes($i);
    $new = Hex::decode(bin2hex($orig));
    if ($orig != $new) {
        exit('error');
    }
}
$elapsed = microtime(true) - $start;

echo "took $elapsed seconds\n";
```

On my machine the original `Hex::decode()` implementation takes about 11s whereas with my alternate function it takes about 2.85s.

To the best of my knowledge it's constant time.

### CODE REVIEW

**Comment by terrafrost** [comment]
It looks like the unit tests pass. The psalm tests seem to be failing however. LMK if you like where I'm going with this and I can try to clean the psalm stuff up. Or you can if you're so inclined lol.

**Comment by paragonie-scott** [comment]
This looks like it'd contain timing leaks. At minimum, `ord()` and `preg_replace_callback()` are suspect.

**Comment by terrafrost** [comment]
Thinking about it I guess there's `str_split` and `array_map` but idk if those are timing safe either and in lieu of knowing I won't bother.

**Comment by paragonie-scott** [comment]
Sorry.

Writing constant-time PHP code is a nontrivial undertaking and often requires delving into the C implementations to see what's happening under the hood.

I appreciate the effort to make our library faster. I'll hopefully find some time next week to delve into these functions to see if there are timing leaks in supported PHP versions.

**Pull request closed without merging**
